// src/react/Tab.js
import React from 'react';

class Tab extends React.Component {
    render() {
        const {
            activeTab,
            tabId,
            title,
            onClick,
            disabled,
            className = ''
        } = this.props;
        const dataTestId = this.props['data-test-id'];
        return (
            <li
                className={`sdc-tab ${
                    activeTab === tabId ? 'sdc-tab-active' : ''
                } ${className}`}
                onClick={disabled ? undefined : onClick}
                data-test-id={dataTestId}
                role="tab"
                disabled={disabled}>
                {title}
            </li>
        );
    }
}

export default Tab;

// src/angular/tabs/tab/tab.component.ts
import { Component, Input } from '@angular/core';

@Component({
    selector: 'sdc-tab',
    template: `
    <div *ngIf="active" class="sdc-tab-content" role="tabpanel">
      <ng-content></ng-content>
    </div>
    `
})
export class TabComponent {
    @Input() public title: string;
    @Input() public active: boolean = false;
    @Input() public disabled: boolean = false;

}
