// src/angular/button.component.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "sdc-button",
  template: `
  <button class="sdc-button sdc-button__{{color}} sdc-button-{{type}}"
       [disabled] = disabled>
        <ng-content></ng-content>
  </button>`
})
export class ButtonComponent {

  @Input() color: string;
  @Input() type: string;
  @Input() disabled: boolean;

  constructor() {
    this.color = 'primary';
    this.type = 'default';
  }

}

// src/react/Button.js
import React from 'react';
import SVGIcon from './SVGIcon.js';

const Button = (props) => {
	let {btnType = 'default', color = 'primary', onClick, disabled, className, iconName, children, ...other} = props;
	return (
		<button onClick={onClick}
		        className={`sdc-button sdc-button-${btnType} sdc-button__${color} ${className || ''} ${iconName ? 'sdc-button__with-icon' : ''}`}
		        disabled={disabled} {...other}>
			<div className={iconName ? `sdc-button-link-icon` : null}>
				{iconName && <SVGIcon className='sdc-button-icon' name={iconName} disabled={disabled}/>}
				<div className='sdc-button-label'>{children}</div>
			</div>
		</button>
	);
};

export default Button;
