// src/angular/buttons/button.component.ts
import {Component, Input} from "@angular/core";


@Component({
    selector: "sdc-button",
    template: `
  <button class="sdc-button sdc-button__{{color}} sdc-button-{{sdcButtonStyle}}"
       [disabled] = disabled>
        <ng-content></ng-content>
  </button>`
})
export class ButtonComponent {

    @Input() color:string;
    @Input() sdcButtonStyle:string;
    @Input() disabled:boolean;

    constructor() {
        this.color = 'primary';
        this.sdcButtonStyle = 'default';
    }
}

<button class="sdc-button sdc-button-default sdc-button__{{ type }} btn-{{ size }}"
        [ngClass]="{'btn-with-icon':icon}"
        [disabled] = "disabled">
        <span>
        <i class = "sdc-icon sdc-icon-left sdc-icon-{{ icon.name }} {{icon.color}}" *ngIf="icon && icon.side == 'left'"></i>
        </span>
                {{ text }}
        <i class = "sdc-icon sdc-icon-right sdc-icon-{{ icon.name }} {{icon.color}}" *ngIf="icon && icon.side == 'right'"></i>
</button>

// src/react/Button.js
import React from 'react';
import SVGIcon from './SVGIcon.js';

const Button = (props) => {
	let {btnType = 'default', color = 'primary', onClick, disabled, className, iconName, iconSize = 'small', children, ...other} = props;
	return (
	    <button onClick={onClick} className={`sdc-button sdc-button-${btnType} sdc-button__${color} ${className || ''} ${iconName ? 'sdc-button__with-icon' : ''}`} disabled={disabled} {...other}>
	      {iconName && <SVGIcon name={iconName} size={iconSize}/>}
	      {children}
	    </button>
	);
};

export default Button;
