// src/angular/form-elements/checkbox/checkbox.component.ts
import {Component, Input, Output, EventEmitter, ViewEncapsulation} from '@angular/core';

@Component({
    selector: 'sdc-checkbox',
    templateUrl: './checkbox.component.html',
    encapsulation: ViewEncapsulation.None
})

export class CheckboxComponent {
    @Input() label:string;
    @Input() checked:boolean;
    @Input() disabled:boolean;
    @Input() value: any;
    @Output() checkedChange:EventEmitter<any> = new EventEmitter<any>();
    toggleState(new_value:boolean) {
        this.value.state = new_value;
        this.checkedChange.emit(this.value);
        alert(this.value.name + ' ' + this.value.state);
    }
}


<div class="sdc-checkbox">
    <input type="checkbox" class="sdc-checkbox__input" [ngModel]="value.state" (ngModelChange)="toggleState($event)" [disabled]="disabled" >
    <label class="sdc-checkbox__label" *ngIf="label" >{{label}}</label>
</div>

// src/react/Checkbox.js
import React from 'react';

class Checkbox extends React.Component {
    render() {
        let {
            checked = false,
            disabled,
            value,
            label,
            inputRef,
            className,
            name,
        } = this.props;
        let dataTestId = this.props['data-test-id'];

        return (
            <div className={`sdc-checkbox ${className || ''}`}>
                <label>
                    <input
                        className="sdc-checkbox__input"
                        ref={inputRef}
                        data-test-id={dataTestId}
                        type="checkbox"
                        checked={checked}
                        name={name}
                        value={value}
                        onChange={e => this.onChange(e)}
                        disabled={disabled}
                    />
                    <span className="sdc-checkbox__label">{label}</span>
                </label>
            </div>
        );
    }

    onChange(e) {
        let { onChange } = this.props;
        if (onChange) {
            onChange(e.target.checked);
        }
    }

    getChecked() {
        return this.props.checked;
    }

    getValue() {
        return this.props.value;
    }
}

export default Checkbox;
